---
title: "02_permanova_cyto"
output: html_document
date: "2025-03-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(include = TRUE, echo = TRUE, message = FALSE, cache=FALSE, warning=FALSE, error = TRUE)
```

```{r}
library(mia)
library(dplyr)
library(tibble)
library(tidyr)
```


```{r}
# Define the data frame of individuals with at least one non-NA value of cytokine (no crp)

  # Define the cytokines without the CRP 
  cytokines_no_crp <- c("IL_1A", "IL_2RA", "IL_3", "IL_12_P40", "IL_16", "IL_18", 
               "CTACK", "GROA", "HGF", "LIF", "MCP_3", "M_CSF", "MIF", 
               "MIG", "B_NGF", "SCF", "SCGF_B", "SDF_1A", "TNF_B", 
               "TRAIL", "IL_1B", "IL_1RA", "IL_2", "IL_4", "IL_5", 
               "IL_6", "IL_7", "IL_8", "IL_9", "IL_10", "IL_12_P70", 
               "IL_13", "IL_15", "IL_17", "EOTAXIN", "FGF_BASIC", 
               "G_CSF", "GM_CSF", "IFN_G", "IP_10", "MCP_1_MCAF", 
               "MIP_1A", "PDGF_BB", "MIP_1B", "RANTES", "TNF_A", "VEGF", "IFN_A2")

   tse <- readRDS("tse_mgs-20241118_104759.rds") # Read TSE
   col_data_df <- as.data.frame(colData(tse)) %>% filter(PROJECT == "FR02") # Remove FR07 

  # Select individuals with at least one non-NA cytokine value
    cytokines_df <- col_data_df [, cytokines_no_crp] 

    cytokines_rownames <- cytokines_df %>% 
    mutate(row_sum = (rowSums(cytokines_df, na.rm = TRUE))) %>%
    filter(row_sum != 0) %>% 
    rownames()
  
  # Subset tse by selected rownames and extract colData
    tse_cyto_subset <- tse [,cytokines_rownames ]
    cl_tse_cyto_subset <- as.data.frame(colData(tse_cyto_subset))

  # Filter the colData; pregnant women, 1M antibiotics,  and low reads, and remove NA covars
    cyto_data_rn <- cl_tse_cyto_subset %>%
    filter((GRAVID == 1 | is.na(GRAVID)) & (BL_USE_RX_J01_1mo == 0) & (total_reads > 50000) & !is.na(CURR_SMOKE) & !is.na(PREVAL_DIAB) & !is.na(BMI) & !is.na(BL_AGE) & !is.na(MEN)) %>% 
      rownames()
    
  # Subset tse by selected rownames and extract colData
    tse_cyto <- tse[, cyto_data_rn]

# Clean the colData

  # Define selected cytokines 
  cytokines <- c("IL_1A", "IL_2RA", "IL_3", "IL_12_P40", "IL_16", "IL_18", 
               "CTACK", "GROA", "HGF", "LIF", "M_CSF", "MIF", 
               "MIG", "B_NGF", "SCF", "SCGF_B", "SDF_1A", "TNF_B", 
               "TRAIL", "IL_1B", "IL_1RA", "IL_2", "IL_4", "IL_5", 
               "IL_6", "IL_7", "IL_8", "IL_9", "IL_10", "IL_12_P70", 
               "IL_13", "IL_17", "EOTAXIN", "FGF_BASIC", 
               "G_CSF", "GM_CSF", "IFN_G", "IP_10", "MCP_1_MCAF", 
               "MIP_1A", "PDGF_BB", "MIP_1B", "RANTES", "TNF_A", "VEGF","CRP")
  
  # Select relevant variables 
  coldata <- as.data.frame(colData(tse_cyto)) %>% select (FID, BL_AGE, MEN, BMI, CURR_SMOKE, PREVAL_DIAB, cytokines)

  # For CRP, replace <0.1 values with min/2 (0.05) and empty strings by NAs
  coldata$CRP <- ifelse(coldata$CRP == "<0.1", 0.05, coldata$CRP)
  coldata$CRP <- as.numeric(coldata$CRP)
  
  # Update colData of tse_cyto to include the two new CRP values 
  coldata_sel <- coldata %>% select (FID, BL_AGE, MEN, BMI, CURR_SMOKE, PREVAL_DIAB, cytokines)
  coldata_sel[cytokines] <- log(coldata_sel[cytokines]) # log transform cytokines
  coldata_sel[cytokines] <- scale(coldata_sel[cytokines]) # scale cytokines 
  SummarizedExperiment::colData(tse_cyto) <- S4Vectors::DataFrame(coldata_sel) # update colData

```

Run permanova
```{r}
# Agglomerate by Species 
tse_cyto <- agglomerateByRank(tse_cyto, rank = "Species")

tse_cyto <- transformAssay(tse_cyto, assay.type = "counts", method = "relabundance")

# add dist matrix 
tse_cyto <- mia::addDissimilarity(tse_cyto, assay.type = "relabundance", method = "bray")

# Run Permanova analysis 
set.seed(1998)
per_results <- lapply(cytokines, function(cytokine) { 
  
  #Build the formula 
  formula <- as.formula(paste0("metadata(tse_cyto)$bray ~ BL_AGE + MEN + BMI + CURR_SMOKE + PREVAL_DIAB + ", cytokine)) 
  
  # Run the analysis 
  vegan::adonis2(formula, data = colData(tse_cyto), permutations = 999, method = "bray", by = "terms", na.action = na.omit) })

names(per_results) <- cytokines

saveRDS(per_results, "permanova_raw_results_cyto.rds")

```

Process results 
```{r}
# Combine the results 
# per_results <- readRDS("permanova_raw_results_cyto.rds")
combined_per_results <- do.call(rbind, per_results)

# Clean rownames 
desired_row_names <- paste(cytokines, cytokines, sep = ".")
combined_per_results <- combined_per_results[rownames(combined_per_results) %in% desired_row_names, ]
rownames(combined_per_results) <- sapply(strsplit(rownames(combined_per_results), "\\."), `[`, 1)

# add q_vals
combined_per_results <- combined_per_results %>% mutate(q_val = p.adjust(`Pr(>F)`, "BH")) %>% arrange (q_val) %>% rownames_to_column()
                     
saveRDS(combined_per_results, "final_permanova_results_cyto.rds")          
knitr::kable(combined_per_results)

writexl::write_xlsx(combined_per_results, "SupTable5_Permanova_results_cyto.xlsx")

```


